name: Sanitizers
env:
  CI_BUILD: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sanitizers:
    strategy:
      matrix:
        sanitizer:
          - UNDEFINED_BEHAVIOR
          - ADDRESS
          - MEMORY
          - THREAD
    name: clang ${{ matrix.sanizier }} sanitizer
    runs-on: ubuntu-latest
    env:
      CC: /usr/bin/clang-10
      CXX: /usr/bin/clang++-10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install clang
        run: |
          sudo apt-get update -m
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 10
      - name: Install conan
        run: |
          sudo apt-get install cmake python3
          sudo pip install --upgrade pip
          sudo pip install --upgrade setuptools
          sudo pip install conan
      - name: Run CMake
        run: cmake -DENABLE_SANITIZER_${{ matrix.sanitizer }}=ON .
      - name: Build sources with ${{ matrix.sanitizer }} sanitizer
        run: cmake --build . --config "Debug"
