name: Static analyze
env:
  CI_BUILD: true

on:
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install cppcheck
        run: |
          sudo apt-get update -m
          sudo apt-get install cppcheck
      - name: Run cppcheck
        run: cppcheck src --force --suppress=missingInclude --enable=all --inconclusive --error-exitcode=1
  clang-tidy:
    strategy:
      matrix:
        - compiler-version: 9
          clang-tidy-version: 9
    runs-on: ubuntu-latest
    env:
      CC: /usr/bin/gcc-${{ matrix.compiler-version) }}
      CXX: /usr/bin/g++-${{ matrix.compiler-version) }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install gcc
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -m
          sudo apt-get install gcc-${{ matrix.compiler-version }}
      - name: Install clang-tidy
        run: |
          sudo apt-get update -m
          sudo apt-get install clang-tidy-${{ matrix.clang-tidy-version }}
      - name: Run clang-tidy
        run: |
          cmake -DENABLE_CLANG_TIDY=ON .
          cmake --build .
